In [1]:
import numpy as np

# Definición del perceptrón (neurona simple)
def perceptron(W, X):
    """Calcula salida del perceptrón para entrada X y pesos W"""
    s = np.sum(W * X)
    print("La suma w1*x1 + w2*x2 + w3*x3 es:", s)
    pred = np.tanh(s)
    return pred

# Ejemplo de entrada
x1, x2, x3 = 0.9, 0.3, 0.5
X = np.array([x1, x2, x3])
print("Inputs X:", X)

# Ejemplo de pesos
w1, w2, w3 = 1, 0.4, 0.3
W = np.array([w1, w2, w3])
print("Pesos W:", W)

# Evaluar la red neuronal
y = perceptron(W, X)
print("El output y de la Red Neuronal es:", y)

# --- VARIOS CONJUNTOS DE ENTRADAS ---
# Matriz de entradas (cada fila es un conjunto diferente)
X_matrix = np.array([
    [0.9, 0.3, 0.5],
    [0.1, 0.8, 0.5],
    [0.5, 0.5, 0.5],
    [1.0, 0.0, 0.0]
])
print("Matriz de inputs X_matrix:")
print(X_matrix)

# Output para cada conjunto de entradas
outputs = []
for X_vec in X_matrix:
    y_out = perceptron(W, X_vec)
    outputs.append(y_out)

print("Outputs para cada fila de entradas:", outputs)


Inputs X: [0.9 0.3 0.5]
Pesos W: [1.  0.4 0.3]
La suma w1*x1 + w2*x2 + w3*x3 es: 1.17
El output y de la Red Neuronal es: 0.8242721703413974
Matriz de inputs X_matrix:
[[0.9 0.3 0.5]
 [0.1 0.8 0.5]
 [0.5 0.5 0.5]
 [1.  0.  0. ]]
La suma w1*x1 + w2*x2 + w3*x3 es: 1.17
La suma w1*x1 + w2*x2 + w3*x3 es: 0.5700000000000001
La suma w1*x1 + w2*x2 + w3*x3 es: 0.85
La suma w1*x1 + w2*x2 + w3*x3 es: 1.0
Outputs para cada fila de entradas: [np.float64(0.8242721703413974), np.float64(0.5153592780074098), np.float64(0.6910694698329306), np.float64(0.7615941559557649)]
